services:

  linkscribe-blueprint:
    container_name: linkscribe-blueprint
    image: blue/linkscribe-blueprint:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=America/Bogota
    logging:
      driver: "journald"
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - input/credenciales/private_jwt.pem:/opt/LinkScribe-Blueprint/input/credenciales/private_jwt.pem:ro
      - input/credenciales/public_jwt.pem:/opt/LinkScribe-Blueprint/input/credenciales/public_jwt.pem:ro

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6:
    
