services:

  LinkScribe-Blueprint:
    container_name: metadata-img-dei
    image: blue/LinkScribe-Blueprint:dev
    build:
      context: ./LinkScribe-Blueprint
      dockerfile: Dockerfile
    environment:
      - TZ=America/Bogota
    logging:
      driver: "journald"
    ports:
      - 8000:8000
    depends_on:
      - mongo
    command: uvicorn main:app --host 0.0.0.0 --proxy-headers --port 8000

    volumes:
      - ./LinkScribe-Blueprint/input/credenciales/private_jwt.pem:/opt/metadata_img_dei_api/input/credenciales/private_jwt.pem:ro
      - ./LinkScribe-Blueprint/input/credenciales/public_jwt.pem:/opt/metadata_img_dei_api/input/credenciales/public_jwt.pem:ro

  mongo:
    image: mongo
    ports:
      - "27017:27017"


